
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 17 23:19:34 ART 2016
//----------------------------------------------------

package compile.il.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int ELSE = 23;
  public static final int SEMICOLON = 13;
  public static final int ASTERISK = 7;
  public static final int EQUALS_SIGN = 16;
  public static final int THEN = 10;
  public static final int WHILE = 22;
  public static final int DOUBLE_EQUALS_SIGN = 25;
  public static final int TRUE = 15;
  public static final int IF = 24;
  public static final int HYPHEN_MINUS = 12;
  public static final int PLUS_SIGN = 11;
  public static final int ID = 3;
  public static final int NUM = 2;
  public static final int DO = 20;
  public static final int LEFT_PARENTHESIS = 5;
  public static final int RIGHT_PARENTHESIS = 6;
  public static final int EOF = 0;
  public static final int DOUBLE_AMPERSAND = 18;
  public static final int DIV = 8;
  public static final int FALSE = 9;
  public static final int error = 1;
  public static final int EXCLAMATION_MARK = 4;
  public static final int LESS_THAN_OR_EQUAL = 19;
  public static final int RIGHT_CURLY_BRACKET = 17;
  public static final int LEFT_CURLY_BRACKET = 14;
  public static final int SKIP = 21;
}

