//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 05 21:21:22 UYST 2016
//----------------------------------------------------

package compile.il.parser;

/**
 * CUP generated interface containing symbol constants.
 */
public interface Tokens {
    /* terminals */
    int ELSE = 22;
    int SEMICOLON = 12;
    int ASTERISK = 7;
    int EQUALS_SIGN = 15;
    int THEN = 9;
    int WHILE = 21;
    int DOUBLE_EQUALS_SIGN = 24;
    int TRUE = 14;
    int IF = 23;
    int HYPHEN_MINUS = 11;
    int PLUS_SIGN = 10;
    int ID = 3;
    int NUM = 2;
    int DO = 19;
    int LEFT_PARENTHESIS = 5;
    int RIGHT_PARENTHESIS = 6;
    int EOF = 0;
    int DOUBLE_AMPERSAND = 17;
    int FALSE = 8;
    int error = 1;
    int EXCLAMATION_MARK = 4;
    int LESS_THAN_OR_EQUAL = 18;
    int RIGHT_CURLY_BRACKET = 16;
    int LEFT_CURLY_BRACKET = 13;
    int SKIP = 20;
}

